package lru_cache

import (
	"fmt"
	"testing"
	"time"
)

func TestLru(t *testing.T) {
	lruCache := NewLRUCache(2, 100*1024*1024)
	fmt.Println(lruCache.GetCapacity())
	fmt.Println("===========")
	fmt.Print("list and err: ")
	fmt.Println(lruCache.ViewLinkedList())
	fmt.Print("map and err: ")
	fmt.Println(lruCache.ViewMap())
	fmt.Print("size and err: ")
	fmt.Println(lruCache.GetSize())
	fmt.Print("get key : 1, res and err: ")
	fmt.Println(lruCache.Get("1"))
	fmt.Print("get key : 2, res and err: ")
	fmt.Println(lruCache.Get("2"))
	fmt.Println("===========")
	lruCache.Set("1", "a", -1)
	fmt.Print("list and err: ")
	fmt.Println(lruCache.ViewLinkedList())
	fmt.Print("map and err: ")
	fmt.Println(lruCache.ViewMap())
	fmt.Print("size and err: ")
	fmt.Println(lruCache.GetSize())
	fmt.Print("get key : 1, res and err: ")
	fmt.Println(lruCache.Get("1"))
	fmt.Print("get key : 2, res and err: ")
	fmt.Println(lruCache.Get("2"))
	fmt.Println("===========")
	lruCache.Set("2", "b", 3)
	fmt.Print("list and err: ")
	fmt.Println(lruCache.ViewLinkedList())
	fmt.Print("map and err: ")
	fmt.Println(lruCache.ViewMap())
	fmt.Print("size and err: ")
	fmt.Println(lruCache.GetSize())
	fmt.Print("get key : 1, res and err: ")
	fmt.Println(lruCache.Get("1"))
	fmt.Print("get key : 2, res and err: ")
	fmt.Println(lruCache.Get("2"))
	fmt.Print("list and err: ")
	fmt.Println(lruCache.ViewLinkedList())
	fmt.Print("map and err: ")
	fmt.Println(lruCache.ViewMap())
	fmt.Print("get key : 1, res and err: ")
	fmt.Println(lruCache.Get("1"))
	fmt.Print("list and err: ")
	fmt.Println(lruCache.ViewLinkedList())
	fmt.Print("map and err: ")
	fmt.Println(lruCache.ViewMap())
	fmt.Println("===========")
	fmt.Print("key 1 expire: ")
	fmt.Println(lruCache.CheckExpire("1"))
	fmt.Print("key 2 expire: ")
	fmt.Println(lruCache.CheckExpire("2"))
	fmt.Println("===========")
	time.Sleep(4 * time.Second)
	fmt.Print("key 1 expire: ")
	fmt.Println(lruCache.CheckExpire("1"))
	fmt.Print("key 2 expire: ")
	fmt.Println(lruCache.CheckExpire("2"))
	fmt.Println("===========")
	fmt.Print("list and err: ")
	fmt.Println(lruCache.ViewLinkedList())
	fmt.Print("map and err: ")
	fmt.Println(lruCache.ViewMap())
	fmt.Print("size and err: ")
	fmt.Println(lruCache.GetSize())
	fmt.Print("get key : 1, res and err: ")
	fmt.Println(lruCache.Get("1"))
	fmt.Print("get key : 2, res and err: ")
	fmt.Println(lruCache.Get("2"))
}
